gishack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('login/', include('login.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login_login, name='login'),
    path('logout/', views.login_logout, name='logout')
]

main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='home'),
    path('map/', views.view_map, name='map'),
    path('about/', views.about_us, name='about'),
    path('jobs/', views.jobs, name='jobs'),
    path('sub/', views.sub, name='sub')
]

login/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models


class UAV(models.Model):
    name = models.CharField('Название', max_length=100)
    oper_id = models.PositiveIntegerField('Оператор')
    base_id = models.PositiveIntegerField('База')
    description = models.TextField('Описание')
    duration = models.PositiveIntegerField('Длительность в полете')
    on_flight = models.BooleanField('В полете')
    destination = models.PositiveBigIntegerField('Направление')
    max_range = models.PositiveIntegerField('Макс. дальность туда и обратно')
    cord_x = models.CharField('Текущее расположение по широте', max_length=100)
    cord_y = models.CharField('Текущее расположение по высоте', max_length=100)
    img_url = models.CharField('URL Изображения', max_length=250)
    
    def __str__(self):
        return f"{self.name} {self.oper_id} {self.on_flight}"
    
    class Meta:
        verbose_name = "БПЛА"
        verbose_name_plural = "БПЛА"


class Base(models.Model):
    name = models.CharField('Название', max_length=100)
    disp_id = models.PositiveIntegerField('Диспетчер')
    description = models.TextField('Описание')
    cord_x = models.CharField('Текущее расположение по широте', max_length=100)
    cord_y = models.CharField('Текущее расположение по высоте', max_length=100)
    active = models.BooleanField('Активный')
    
    def __str__(self):
        return f"{self.name} {self.disp_id}"
    
    class Meta:
        verbose_name = "База"
        verbose_name_plural = "Базы"


class Marker(models.Model):
    name = models.CharField('Название', max_length=100)
    uav_id = models.PositiveIntegerField('БПЛА')
    description = models.TextField('Описание')
    state = models.PositiveIntegerField('Состояние')
    marker = models.PositiveIntegerField('Маркер')
    cord_x = models.CharField('Расположение по широте', max_length=100)
    cord_y = models.CharField('Расположение по высоте', max_length=100)
    
    def __str__(self):
        return f"{self.name} {self.cord_x} {self.cord_y}"
    
    class Meta:
        verbose_name = "Маркер"
        verbose_name_plural = "Маркеры"

login/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    username = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


def login_login(request):
    if request.user.is_authenticated:
        return redirect(request.META.get('HTTP_REFERER', '/'))
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password1')
        
        user = authenticate(username=username, password=password)
        
        if user:
            login(request, user)
            return redirect('main:home')
        else:
            data = {
                'error': 'Введенные имя пользователя или пароль неверные'
            }
            return render(request, 'login/login.html', data)
    else:
        return render(request, 'login/login.html')


def login_logout(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER', '/'))

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .models import UAV, Base, Marker

def index(request):
    return render(request, 'main/index.html')

def view_map(request):
    return render(request, 'main/map.html')

def about_us(request):
    return render(request, 'main/about.html')

def jobs(request):
    return render(request, 'main/jobs.html')

def sub(request):
    if not request.user.is_authenticated:
        return redirect(request.META.get('HTTP_REFERER', '/'))
    print(request.user.groups)
    if request.user.groups.filter(name='диспетчеры').exists():
        data = dict()
        base = Base.objects.filter(disp_id=request.user.id)[0]
        uavs = UAV.objects.filter(base_id=base.id)
        markers = Marker.objects.all()
        uavs_front = []
        markers_front = []
        for uav in uavs:
            current = [uav.img_url, uav.name, uav.on_flight, User.objects.filter(id=uav.oper_id)[0].username, uav.max_range, uav.cord_x, uav.cord_y, uav.destination, uav.duration, uav.id]
            uavs_front.append(current)
        for mk in markers:
            current = [mk.id, mk.name, mk.uav_id, mk.description, mk.state, mk.marker, mk.cord_x, mk.cord_y]
            markers_front.append(current)
        data['uavs'] = uavs_front
        data['base'] = base
        data['markers'] = markers_front
        data['map'] = 'https://static-maps.yandex.ru/1.x/?ll=111.126512,63.424022&size=650,450&z=7&l=map&pt='
        for base in Base.objects.all():
            data['map'] += f'{base.cord_x},{base.cord_y},pm2bl~'
        for uav in UAV.objects.all():
            data['map'] += f'{uav.cord_x},{uav.cord_y},pm2wtm{uav.id}~'
        for marker in Marker.objects.all():
            data['map'] += f'{marker.cord_x},{marker.cord_y},'
            if marker.state == 0:
                data['map'] += f'pm2orm{marker.id}~'
            elif marker.state == 1:
                data['map'] += f'pm2grm{marker.id}~'
            else:
                data['map'] += f'pm2rdm{marker.id}~'
        data['map'] = data['map'][:-1]
        print(data['map'])
        return render(request, 'main/sub-disp.html', data)
    if request.user.groups.filter(name='операторы').exists():
        return render(request, 'main/sub-oper.html')
    return redirect(request.META.get('HTTP_REFERER', '/'))

login/templates/login/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.2.1/css/fontawesome.min.css">
    <link rel="stylesheet" href="{% static 'login/css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

login/templates/login/login.html
{% extends 'login/layout.html' %}

{% block title %}Вход{% endblock %}

{% block content %}
    <form class="login-form border flex-column mb-3" method="post">
        {% csrf_token %}
        <h3 class="login-title">Вход</h3>
        {% if error %}
            <div class="mb-3 text-bg-danger p-3 error-h fw-semibold text-center">
                {{ error }}
            </div>
        {% endif %}
        <div class="mb-3">
            <label for="id_username" class="form-label">Имя пользователя</label>
            <input type="text" name="username" maxlength="20" class="form-control" id="id_username" autofocus required>
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Пароль</label>
            <input type="password" name="password1" class="form-control password-input" autocomplete="new-password" id="id_password1" required>
        </div>
        <button type="submit" class="btn btn-primary">Войти</button>
    </form>
{% endblock %}

main/templates/main/about.html
{% extends "main/layout.html" %}
{% load static %}
{% block title %}О нас{% endblock %}



{% block body %}
    <main>
        <div class="text-center">
            <div class="d-flex flex-column mb-3 sub-h">
                <h1 class="fw-bold title">О нас</h1>
            </div>
        </div>
    </main>

    <div class="trt2">
        <div class="container">
            <div class="row">
                <div class="col-sm left">
                    <h1 class="fw-bold col-sm">Кто мы?</h1>
                    <p>Мы - команда начинающих разработчиков и энтузиастов, использующих новейшие технологии при работе с нашими проектами. Мы приложим все усилия, чтобы подарить Вам комфорт и счастье.</p>
                </div>
                <img class="col-sm title-mascot" src="{% static 'main/img/rafiki.png' %}">
            </div>
        </div>
    </div>

    <div class="trt3">
        <div class="container">
            <div class="row">
                <img class="col-sm title-mascot-2" src="{% static 'main/img/pana.png' %}">
                <div class="col-sm left">
                    <h1 class="fw-bold col-sm">Что мы делаем?</h1>
                    <p>Мы дарим Вам практичный и приятный в использовании продукт,
                        чтобы Вам было удобно. В будущем мы хотим воплощать в жизнь всё
                        больше интересных и качественных проектов.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/footer.html
{% load static %}

<footer>
    <div class="row justify-content-md-center footer-h">
        <div class="footer-el col-sm d-flex justify-content-around">
            <div class="footer-el-h d-flex flex-column mb-3">
                <a href="{% url 'main:home' %}" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
                    <img class="header-logo" src="{% static 'main/img/logo.png' %}" alt="" height="60px">
                </a>
                <p class="text-logo"> FIREFLY YKT предоставляет вам<br>дроны, необходимые для<br>мониторинга действительных лесных<br>пожаров.</p>
                <a href="#">
                    <img src="{% static 'main/img/telegramlogo.png' %}">
                    Telegram
                </a>
            </div>
            <div class="footer-el-h d-flex flex-column mb-3">
                <span class="footer-title fw-bold">Компания</span>
                <a href="{% url 'main:about' %}">О нас</a>
                <a href="{% url 'main:jobs' %}">Вакансии</a>
            </div>
            <div class="footer-el-h d-flex flex-column mb-3">
                <span class="footer-title fw-bold">Помощь</span>
                <a href="https://t.me/rlycluster">Тех.Поддержка</a>
                <a href="https://t.me/yarrichelli">Условия пользования</a>
                <a href="#">Политика конфиденциальности</a>
            </div>
        </div>
    </div>
</footer>

main/templates/main/header.html
{% load static %}

<header>
    <nav class="navbar navbar-expand-lg" style="background-color: #fff;" data-bs-theme="light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{%  url 'main:home' %}">
                <img class="header-logo" src="{% static 'main/img/logo.png' %}" alt="" height="60px">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link header-btn" href="{%  url 'main:home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link header-btn" href="{%  url 'main:map' %}">Карта</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link header-btn" href="{%  url 'main:jobs' %}">Вакансии</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link header-btn" href="{%  url 'main:about' %}">О нас</a>
                    </li>
                </ul>
                <div class="d-flex">
                    {% if user.is_authenticated %}
                        <a class="btn btn-outline-danger btn-login" href="{% url 'main:sub' %}">{{ user.username }} - Вход в СУБ</a>
                    {% else %}
                        <a class="btn btn-outline-dark btn-login" href="{% url 'login:login' %}">Авторизация</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

main/templates/main/index.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}Главная{% endblock %}

{% block body %}
    <main>
        <div class="trt1 container">
            <div class="row">
                <div class="col-sm left">
                    <h1 class="fw-bold col-sm trt1-title">Мониторинг<br>лесных<br>пожаров</h1>
                    <p>Наши дроны помогут вам отслеживать лесные<br>пожары без выезда на точку </p>
                    <form class="d-flex search-label" role="search">
                        <input class="form-control" type="search" placeholder="Район / улус" aria-label="Search">
                        <button class="btn btn-outline-dark btn-search" type="submit">Поиск</button>
                    </form>
                </div>
                <img class="col-sm img-forest" src="{% static 'main/img/forest.png' %}">
            </div>
        </div>
        <div class="trt2 container">
            <h1 class="fw-bold trt-title">Статистика за 2022 год</h1>
            <div class="row">
                <img class="col-sm img-yakutia" src="{% static 'main/img/yakutia.png' %}">
                <div class="col-sm right">
                    <img style="margin-bottom: 20px;" src="{% static 'main/img/result1.png' %}" alt="result1.png">
                    <img style="margin-bottom: 20px;" src="{% static 'main/img/result2.png' %}" alt="result1.png">
                    <img style="margin-bottom: 20px;" src="{% static 'main/img/result3.png' %}" alt="result1.png">
                    <img style="margin-bottom: 20px;" src="{% static 'main/img/result4.png' %}" alt="result1.png">
                </div>
            </div>
        </div>
        <div class="trt3 container">
            <h1 class="fw-bold trt-title">Вероятность пожара</h1>
            <div class="row">
                <img class="col-sm img-pozhar" src="{% static 'main/img/pozhar.png' %}">
                <div class="col-sm">
                        <img style="width: 100%; margin-bottom: 30px;" src="{% static 'main/img/redgroup.png' %}" alt="redgroup">
                        <img style="width: 100%;" src="{% static 'main/img/orangegroup.png' %}" alt="orangegroup.png">
                </div>
            </div>
        </div>
    </main>
{% endblock %}

main/templates/main/jobs.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}Вакансии{% endblock %}

{% block body %}
    <main>
        <div class="trt1 container">
            <h1 class="fw-bold jobs-title">Вакансии</h1>
            <div class="jobs-form-h d-flex justify-content-end">
                <form class="jobs-form flex-column d-flex" method="post">
                    {% csrf_token %}
                    <h2 class="jobs-zt">Заполните заявку</h2>
                    <input type="text" class="form-control jobs-form-input mb-3" placeholder="Ваш город" required>
                    <input type="tel" class="form-control jobs-form-input mb-3" placeholder="+7 (999) 999-99-99" required>
                    <input type="text" class="form-control jobs-form-input mb-3" placeholder="Специализация" required>
                    <button type="submit" class="btn btn-outline-dark jobs-form-btn mb-3">Отправить заявку</button>
                    <p class="mb-3">Отправляя заявку, вы принимаете Политику конфиденциальности и соглашаясь получать звонки и SMS от FireFly, а также соглашаетесь на переписку с нами в Telegram</p>
                </form>
            </div>
        </div>
        <div class="trt2 container">
            <h1 class="fw-bold jobs-trt2-title">Приходите работать к нам</h1>
            <table class="table">
                <h3 class="table-title">Специализации</h3>
                <tbody>
                    <tr>
                        <td>
                            <div class="footer-el-h d-flex flex-column mb-3">
                                <span>Роль</span>
                                <span class="fw-bold">Оператор дрона</span>
                            </div>
                        </td>
                        <td>
                            <div class="footer-el-h d-flex flex-column mb-3">
                                <span>Требования</span>
                                <span class="fw-bold">Хороший интернет, ПК</span>
                            </div>
                        </td>
                        <td>
                            <div class="footer-el-h d-flex flex-column mb-3">
                                <span>Обязанности</span>
                                <span class="fw-bold">Оперативный контроль</span>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <div class="footer-el-h d-flex flex-column mb-3">
                                <span>Роль</span>
                                <span class="fw-bold">Диспетчер</span>
                            </div>
                        </td>
                        <td>
                            <div class="footer-el-h d-flex flex-column mb-3">
                                <span>Требования</span>
                                <span class="fw-bold">8 часовая смена</span>
                            </div>
                        </td>
                        <td>
                            <div class="footer-el-h d-flex flex-column mb-3">
                                <span>Обязанности</span>
                                <span class="fw-bold">Контроль технического <br> состояния беспилотника</span>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
            <a href="https://t.me/yarrichelli" class="btn btn-outline-dark btn-more">Подробнее</a>
        </div>
    </main>
{% endblock %}

main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="{% static 'main/css/styles.css' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        {% include "main/header.html" %}
        {% block body %}
        
        {% endblock %}
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"
        ></script>
        {% include "main/footer.html" %}
    </body>
</html>

main/templates/main/map.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}Карта пожаров{% endblock %}

{% block body %}
    <main>
        <div class="trt1 container">
            <h1 class="fw-bold map-title">Лесные пожары в Якутии</h1>
            <iframe src="https://fires.ru/?z=4&amp;x=128.05664062500003&amp;y=65.14611484756375&amp;dt=10.08.2021" style="width:100%; height:500px;"></iframe>
        </div>
        <div class="trt2 container">
            <h1 class="map-stats">Статистика за 2020-2022</h1>
            <div class="row">
                <div class="col">
                    <h2 class="map-stats-text">2020</h2>
                    <img class="map-stats-img" src="{% static 'main/img/2020.png' %}" alt="">
                </div>
                <div class="col">
                    <h2 class="map-stats-text">2021</h2>
                    <img class="map-stats-img" src="{% static 'main/img/2021.png' %}" alt="">
                </div>
                <div class="col">
                    <h2 class="map-stats-text">2022</h2>
                    <img class="map-stats-img" src="{% static 'main/img/2022.png' %}" alt="">   
                </div>
            </div>
        </div>
        <div class="trt3 container">
            <h1 class="map-stats">Расположение баз беспилотников</h1>
            <img class="map-img" src="{% static 'main/img/map.png' %}" alt="" style="max-width: 90%;">
        </div>
    </main>
{% endblock %}

main/templates/main/sub-disp.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"/>
        <link rel="stylesheet" href="{% static 'main/css/sub.css' %}">
        <title>СУБ</title>
    </head>
    <body>
        <main class="container">
            <h1 class="title">Система Управления Беспилотниками (СУБ) - диспетчер</h1>
            <div class="uav-trt d-flex flex-column">
                <h2 class="uav-trt-title">Беспилотники в базе "{{ base.name }}"</h2>
                {% for uav in uavs %}
                    <div class="uav-card d-flex flex-row">
                        <img class="uav-img" src="{{ uav.0 }}">
                        <h3 class="uav-name">{{ uav.1 }}</h3>
                        <div class="uav-static-info d-flex flex-column">
                            {% if uav.2 %}
                                <span class="uav-state">В полете</span>
                            {% else %}
                                <span class="uav-state">На базе</span>
                            {% endif %}
                            <span class="uav-oper">Оператор: {{ uav.3 }}</span>
                            <span class="uav-range">Покрытие: {{ uav.4 }} км</span>
                            <span>На карте: {{ uav.9 }}</span>
                        </div>
                        <div class="uav-cur-info d-flex flex-column">
                            <span>Текущие координаты:</span>
                            <span>x: {{ uav.5 }}</span>
                            <span>y: {{ uav.6 }}</span>
                            {% if uav.7 == 0 %}
                                <span>Ждет на базе</span>
                            {% else %}
                                <span>Направляется к точке {{ uav.7 }}</span>
                            {% endif %}
                            <span>В воздухе: {{ uav.8 }} мин.</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="d-flex flex-row justify-content-center map  ">
                <img src="{{ map }}" alt="">
            </div>
            <div class="markers-trt d-flex flex-column">
                <h2>Маркеры на карте</h2>
                {% for mk in markers %}
                    <div class="marker-card d-flex flex-row">
                        <h3 class="mark-name">{{ mk.0 }}</h3>
                        <div class="uav-static-info d-flex flex-column">
                            {% if mk.2 == 0 %}
                                <span>БПЛА не назначен</span>
                            {% else %}
                                <span>Номер БПЛА: {{ mk.2 }}</span>
                            {% endif %}
                            <span>{{ mk.3 }}</span>
                        </div>
                        <div class="uav-cur-info d-flex flex-column">
                            <span>Координаты:</span>
                            <span>x: {{ mk.6 }}</span>
                            <span>y: {{ mk.7 }}</span>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </main>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

main/templates/main/sub-oper.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}СУБ{% endblock %}

{% block body %}
    <main>
        <h1>Система Управления Беспилотниками (СУБ)</h1>
    </main>
{% endblock %}

main/templates/main/sub.html
{% extends "main/layout.html" %}
{% load static %}

{% block title %}СУБ{% endblock %}

{% block body %}
    
{% endblock %}